In [53]:
import numpy as np
import torch
import torch.optim as optim

from pbo.agents.q_networks import QFullyConnectedNet

layer_dimension = 3
random_weights_range = 10
gamma = 0.99

Q_network = QFullyConnectedNet(
    layer_dimension=layer_dimension,
    random_weights_range=random_weights_range,
    max_action=10,
    n_discrete_actions=100,
)

optimizer = optim.SGD(Q_network.parameters(), lr=1, momentum=0.9)

weights = Q_network.get_random_weights() * 0
weights[6] = -100000
weights[-1] = 10000
Q_network.set_weights(weights)


optimizer.zero_grad()

loss = Q_network(torch.Tensor([1]), torch.Tensor([1]))
loss.backward()

optimizer.step()

for i in Q_network.parameters():
    print(i)

Parameter containing:
tensor([[-0., 0.],
        [0., 0.],
        [-0., 0.]], requires_grad=True)
Parameter containing:
tensor([-100000.,      -0.,      -0.], requires_grad=True)
Parameter containing:
tensor([[0., -0., 0.]], requires_grad=True)
Parameter containing:
tensor([9999.], requires_grad=True)


In [55]:
Q_network.network.linear_2.bias

Parameter containing:
tensor([9999.], requires_grad=True)

In [54]:
Q_network(torch.Tensor([1]), torch.Tensor([1]))

tensor([9999.], grad_fn=<AddBackward0>)

In [52]:
optimizer.param_groups

[{'params': [Parameter containing:
   tensor([[0., -0.],
           [0., 0.],
           [0., 0.]], requires_grad=True),
   Parameter containing:
   tensor([-100000.,       0.,       0.], requires_grad=True),
   Parameter containing:
   tensor([[0., 0., -0.]], requires_grad=True),
   Parameter containing:
   tensor([99.], requires_grad=True)],
  'lr': 1,
  'momentum': 0.9,
  'dampening': 0,
  'weight_decay': 0,
  'nesterov': False,
  'maximize': False}]